### ISSUE TITLE
Problem with TCPSecurePortCheck

### ISSUE THREAD

**Issue by sandhyamohang** [newrelic/quickstarts-synthetics-library#10]
Hi,
The TLS module is unable to load. When check with NR support, they have asked to check with github.

Here is the error.

Script execution failed: Error: Module "tls" cannot be loaded
Error: Module "tls" cannot be loaded

Thanks

**Comment by bpeckNR** [comment]
Are you getting this error on a private minion? The TLS module was added to the private minion in [Containerized Private Minion version 3.0.32 in December 2020](https://docs.newrelic.com/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/). If you are running an older version of the private minion you will need to upgrade to 3.0.32 or newer to use this module.

**Comment by sandhyamohang** [comment]
Yes I find the below information 

Current Minion build number :3.0.31 

So I need to have minimum 3.0.32 to get the TLS module to work.

Thanks

**Comment by kidk** [comment]
Thanks you for the update.

We will now close this ticket, please re-open it if the issue returns.
