### ISSUE TITLE
Broken Link Checking Script

### ISSUE THREAD

**Issue by Ephesoft-Stitus** [newrelic/quickstarts-synthetics-library#11]
## Summary
Add the script for the new broken link checker synthetic type here.

## Desired Behavior
The same script that is used internally to create the broken link check synthetic type is made available in this repo.

## Additional context
Currently, the only way to create a broken link check synthetic is via the UI.  Adding the script used to create that type of synthetic here will allow others to programmatically create a broken link checking synthetic without having to duplicate the effort of creating the script and ensures best practices are being followed.

**Comment by philweber** [comment]
@Ephesoft-Stitus I have created a Broken Link Checker script and submitted it as a [pull request](https://github.com/newrelic/quickstarts-synthetics-library/pull/13). Until it is merged, you may download it from here: https://github.com/philweber/quickstarts-synthetics-library/tree/main/library/BrokenLinkChecker

**Comment by kidk** [comment]
https://github.com/newrelic/quickstarts-synthetics-library/pull/13 has been merged. Thanks @Ephesoft-Stitus for the suggestion and @philweber for the fix 🥳
